name: baby_elephant
description: A mastodon client for smart watches
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mastodon_api:
    git: git@github.com:mastodon-dart/mastodon-api.git
  pull_to_refresh: ^2.0.0
  flutter_widget_from_html_core: ^0.14.9
  flutter_native_splash: ^2.2.16
  wearable_rotary: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.1.2
  shared_preferences: ^2.2.2
  flutter_wear_os_connectivity: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
    android: "launcher_icon"
    image_path: "assets/elephant.png"

flutter:
  uses-material-design: true

  assets:
      - assets/elephant.png

flutter_native_splash:
    color: "#ffffff"
    image: assets/elephant.png

