name: baby_elephant
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  flutter_native_splash: ^2.2.16
  mastodon_oauth2: ^0.1.1
  mastodon_api: ^0.2.2
  wearable_communicator: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/elephant.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/elephant.png

flutter_icons:
  android: "launcher_icon"  
  image_path: "assets/elephant.png"


